spring:
    datasource:
        url: 'jdbc:postgresql://localhost:5432/jwt_security'
        username: postgres
        password: pass
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
